### ISSUE TITLE
请教一下，output链是先于路由决策执行还是后于路由决策执行，或者先后都做了路由决策呢？

### ISSUE THREAD

**Issue by seriousgong** [chaos-mesh/chaos-tproxy#48]

**Comment by Andrewmatilde** [comment]
确实不行，基本上都是放在PREROUTING里set-mark的。同一NETNS出口流量一般只有客制协议栈可以直接搞透明代理。

**Comment by Andrewmatilde** [comment]
> 网上的图上路由决策大都在output之前，如果是这样的话，output链中fwmark是怎么能做到让数据包重走路由的

所谓的重走路由只是把从外部来的走Forward链的包转成法向本地。

**Comment by seriousgong** [comment]
> 

@Andrewmatilde  
原本chaos-tproxy服务是注入到服务端容器的，那么客户端的流量经过经过prerouting就到了chaos-tproxy服务，序列化成httprequest后在往服务端进程发,这里因为给流量标记了ignore mark，所以发的请求可以到服务端。然后服务端发出响应，这个时候output链给这些数据包打上fwmark,匹配到重新发往lo网卡,因为重新经过prerouting,所以响应也到了chaos-tproxy服务.最终实现请求\响应的一些操作.是这样理解吗?
按我理解来看,路由决策是先于output的,然后mangle表的output链怎么实现重走路由的这里不是很理解.从图上看是mangle表的output链之后有reroute-check,不知道是不是reroute-check做了这个事
![image](https://user-images.githubusercontent.com/56463479/169438397-96145952-bd03-4a92-9ac2-a0869b8136b2.png)

**Comment by Andrewmatilde** [comment]
chaos-tproxy的代理和服务端在两个NetNS，中间打了一个路由层，所以就没有这种问题。
